export type ModalContentType =
  | ""
  | "createChat"
  | "deleteChat"
  | "deleteChatMessages"
  | "editChat"
  | "createChatStandardPhrase"
  | "editChatStandardPhrase"
  | "deleteChatStandardPhrase"
  | "createFavorite"
  | "editFavorite"
  | "deleteFavorite"
  | "createWriter"
  | "emojiSelect"
  | "modelsList";
