import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalFrame } from "@/components/templates/GlobalFrame/GlobalFrame.template";
import { Provider } from "@/components/templates/Provider/Provider.template";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="ja">
        <body className={inter.className}>
          <GlobalFrame>{children}</GlobalFrame>
        </body>
      </html>
    </Provider>
  );
}
