export const queryKeysConfig = {
  GET_CHAT: "GET_CHAT",
  GET_CHAT_MESSAGE: "GET_CHAT_MESSAGE",
  GET_CHAT_STANDARD_PHRASE: "GET_CHAT_STANDARD_PHRASE",
  GET_CLIPBOARD: "GET_CLIPBOARD",
  GET_FAVORITE: "GET_FAVORITE",
  GET_MEMO: "GET_MEMO",
  GET_USER: "GET_USER",
};
